// Requires a seeded, disposable local database and running app; no notification worker.
import assert from "node:assert/strict";
import { chromium } from "playwright";
import { DateTime } from "luxon";
import pg from "pg";
const base = process.env.E2E_BASE_URL ?? "http://127.0.0.1:3006";
const database = process.env.DATABASE_URL_TEST;
if (!database || ![new URL(base).hostname, new URL(database).hostname].every((h) => ["localhost", "127.0.0.1"].includes(h))) throw new Error("Use a local app and explicit local test database.");
const pool = new pg.Pool({ connectionString: database });
const browser = await chromium.launch(process.env.PW_CHROMIUM ? { executablePath: process.env.PW_CHROMIUM } : {});
try {
  const page = await browser.newPage({ viewport: { width: 1360, height: 1000 } });
  await page.goto(`${base}/login`);
  await page.locator('input[name="email"]').fill("demo@itckar.local");
  await page.locator('input[name="password"]').fill("demo1234");
  await page.getByRole("button", { name: /Prihlásiť/ }).click();
  await page.waitForURL(/\/app/);
  const day = DateTime.now().setZone("Europe/Prague").plus({ weeks: 3 }).startOf("week");
  await page.goto(`${base}/app/appointments/new?date=${day.toISODate()}&time=10:00`);
  await page.locator('input[name="serviceIds"]').first().check();
  await page.getByRole("button", { name: "Nový", exact: true }).click();
  await page.locator("#firstName").fill("Presun E2E");
  await page.getByRole("button", { name: "Vytvoriť rezerváciu" }).click();
  await page.waitForURL(/\/app\/appointments\/[0-9a-f-]+$/);
  const id = page.url().split("/").at(-1);
  const read = async () => (await pool.query("SELECT start_at, public_token FROM appointment WHERE id = $1", [id])).rows[0];
  const original = await read();
  await page.getByText("Presunúť rezerváciu", { exact: true }).click();
  await page.getByLabel("Nový dátum").fill(day.plus({ days: 6 }).toISODate()); // closed Sunday
  await page.getByRole("button", { name: "Potvrdiť presun" }).click();
  await page.getByRole("alert").waitFor();
  assert.equal((await read()).start_at.getTime(), original.start_at.getTime());
  await page.getByLabel("Nový dátum").fill(day.plus({ days: 1 }).toISODate());
  await page.getByLabel("Nový čas").fill("11:00");
  await page.getByRole("button", { name: "Potvrdiť presun" }).click();
  await page.getByRole("status").filter({ hasText: "Termín bol presunutý" }).waitFor();
  const updated = await read();
  assert.equal(updated.start_at.getTime(), day.plus({ days: 1 }).set({ hour: 11 }).toMillis());
  assert.equal(updated.public_token, original.public_token);
  await page.goto(`${base}/app/calendar?date=${day.plus({ days: 1 }).toISODate()}`);
  const event = page.locator(`[data-move-id="${id}"]`).first();
  const box = await event.boundingBox();
  assert.ok(box);
  await page.mouse.move(box.x + 15, box.y + 5);
  await page.mouse.down();
  await page.mouse.move(box.x + 15, box.y + 20, { steps: 5 });
  await page.mouse.move(box.x + 15, box.y + 77, { steps: 8 });
  await page.mouse.up();
  const dialog = page.getByRole("dialog");
  await dialog.waitFor();
  assert.equal(await dialog.getByLabel("Nový čas").inputValue(), "12:00");
  assert.equal((await read()).start_at.getTime(), updated.start_at.getTime(), "drag only proposes a change");
  await dialog.getByRole("button", { name: "Potvrdiť presun" }).click();
  await dialog.waitFor({ state: "detached" });
  assert.equal((await read()).start_at.getTime(), day.plus({ days: 1 }).set({ hour: 12 }).toMillis());
  await page.goto(`${base}/r/${original.public_token}`);
  assert.ok((await page.textContent("body")).includes("12:00"), "public management reflects the move");
  console.log("OK: closed-day rejection, detail form, preserved public link, drag preview, confirmed move, public updated time");
} finally { await browser.close(); await pool.end(); }
